//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Feroza.TecniPart.Infraestructura.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AplicacionesData
    {
        public int IdAplicaciones { get; set; }
        public int IdVehiculos { get; set; }
        public string CodigoOem { get; set; }
    
        public virtual ReferenciasData Referencias { get; set; }
        public virtual ProductosData Productos { get; set; }
    }
}
