//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Feroza.TecniPart.Infraestructura.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogosData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatalogosData()
        {
            this.CatalogoDetalles = new HashSet<CatalogoDetallesData>();
        }
    
        public long IdCatalogos { get; set; }
        public int IdVehiculos { get; set; }
        public int IdSistemas { get; set; }
        public int IdSubSistemas { get; set; }
        public byte[] ImagenCatalogo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatalogoDetallesData> CatalogoDetalles { get; set; }
        public virtual VehiculosData Vehiculos { get; set; }
        public virtual SistemasData Sistemas { get; set; }
        public virtual SubSistemasData SubSistemas { get; set; }
    }
}
