//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Feroza.TecniPart.Infraestructura.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarcasData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MarcasData()
        {
            this.Vehiculos = new HashSet<VehiculosData>();
        }
    
        public int IdMarcas { get; set; }
        public string Descripcion { get; set; }
        public string Sigla { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehiculosData> Vehiculos { get; set; }
    }
}
