//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Feroza.TecniPart.Infraestructura.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubSistemasData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubSistemasData()
        {
            this.Catalogos = new HashSet<CatalogosData>();
            this.VehiculoSubSistemas = new HashSet<VehiculoSubSistemasData>();
        }
    
        public int IdSubSistemas { get; set; }
        public string Descripcion { get; set; }
        public int IdSistemas { get; set; }
        public int IdEstadoMaestras { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatalogosData> Catalogos { get; set; }
        public virtual SistemasData Sistemas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehiculoSubSistemasData> VehiculoSubSistemas { get; set; }
        public virtual EstadoMaestrasData EstadoMaestras { get; set; }
    }
}
