//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Feroza.TecniPart.Infraestructura.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehiculoSubSistemasData
    {
        public int IdVehiculoSubSistemas { get; set; }
        public int IdVehiculoSistemas { get; set; }
        public int IdSubSistemas { get; set; }
    
        public virtual VehiculoSistemasData VehiculoSistemas { get; set; }
        public virtual SubSistemasData SubSistemas { get; set; }
    }
}
