//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Feroza.TecniPart.Infraestructura.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehiculos()
        {
            this.Aplicaciones = new HashSet<Aplicaciones>();
            this.Catalogos = new HashSet<Catalogos>();
        }
    
        public int IdVehiculos { get; set; }
        public string Descripcion { get; set; }
        public byte[] ImagenVehiculo { get; set; }
        public int IdFabricantes { get; set; }
        public int IdMarca { get; set; }
        public string Ango { get; set; }
        public string Comentario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aplicaciones> Aplicaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalogos> Catalogos { get; set; }
        public virtual Fabricantes Fabricantes { get; set; }
        public virtual Marcas Marcas { get; set; }
    }
}
